// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRk8aPiq5TRYzgu2aOw1r7Q5KltZgLUM4',
    appId: '1:102756319116:web:958b1ff341bf302d82a0a9',
    messagingSenderId: '102756319116',
    projectId: 'skincare-logger',
    authDomain: 'skincare-logger.firebaseapp.com',
    storageBucket: 'skincare-logger.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkiPfaobHsgy3PFcQ5ROz7fxaXGtQsNx0',
    appId: '1:102756319116:android:bf41fdeac8ce5b5c82a0a9',
    messagingSenderId: '102756319116',
    projectId: 'skincare-logger',
    storageBucket: 'skincare-logger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJy9ZrbMlCbF_yNq-7NcY_v1PwoD8M5FU',
    appId: '1:102756319116:ios:2994abf80b65f5eb82a0a9',
    messagingSenderId: '102756319116',
    projectId: 'skincare-logger',
    storageBucket: 'skincare-logger.appspot.com',
    iosBundleId: 'com.example.skincareLogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJy9ZrbMlCbF_yNq-7NcY_v1PwoD8M5FU',
    appId: '1:102756319116:ios:b9045f7bc08caef482a0a9',
    messagingSenderId: '102756319116',
    projectId: 'skincare-logger',
    storageBucket: 'skincare-logger.appspot.com',
    iosBundleId: 'com.example.skincareLogger.RunnerTests',
  );
}
